### ISSUE TITLE
please bump dependency on rand to branch v0.8

### ISSUE THREAD

**Issue by jonassmedegaard** [maidsafe/qjsonrpc#18]
This crate depends on `rand` v0.7. It's only reverse dependency, `sn_api`, depends on both v0.7 and v0.8 of `rand`, where v0.7 seemingly is used only due to its use by `qjsonrpc`and `ed25519-dalek`. With `ed25519-dalek` about toissue a new release where they move to `rust` v0.8 (potentially very soon - 4 days ago a git commit talked about "rc.1 status"), `qjsonrpc` may become the last blocker for Safenet loosing some baggage, which has been expressed as a wish at https://github.com/maidsafe/safe_network/issues/1147

Therefore, please consider migrating to rand v0.8.

**Comment by davidrusu** [comment]
thanks for the report, bumped in #19
